{
 "title": "Chaos Experiments Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Chaos Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Chaos Experiments Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "litmuschaos_cluster_scoped_experiments_run_count",
     "legendFormat": "Total Experiments"
    }
   ]
  },
  {
   "title": "Chaos Experiments Detail",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "litmuschaos_cluster_scoped_failed_experiments",
     "legendFormat": "Failed Experiments"
    },
    {
     "expr": "litmuschaos_cluster_scoped_passed_experiments",
     "legendFormat": "Passed Experiments"
    },
    {
     "expr": "litmuschaos_cluster_scoped_awaited_experiments",
     "legendFormat": "Awaited Experiments"
    }
   ]
  },
  {
   "title": "Total Experiments Run",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(litmuschaos_awaited_experiments) + sum(litmuschaos_passed_experiments) + sum(litmuschaos_failed_experiments)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Passed Experiments",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(litmuschaos_passed_experiments)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Experiments",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(litmuschaos_failed_experiments)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Awaited Experiments",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(litmuschaos_awaited_experiments)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chaos Experiment Probe Success Percentage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "litmuschaos_probe_success_percentage",
     "legendFormat": "{{chaosengine_name}}"
    }
   ]
  },
  {
   "title": "Chaos Experiment Total Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "litmuschaos_experiment_total_duration",
     "legendFormat": "{{chaosengine_name}}"
    }
   ]
  }
 ]
}