{
 "title": "Chaos Experiments Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Chaos Exporter Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Chaos Experiments Duration",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "litmuschaos_experiment_total_duration",
     "legendFormat": "{{chaosengine_name}}"
    }
   ]
  },
  {
   "title": "Total Experiments",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "litmuschaos_cluster_scoped_experiments_installed_count",
     "legendFormat": "Total Experiments"
    }
   ]
  },
  {
   "title": "Awaited Experiments",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 8 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "litmuschaos_cluster_scoped_awaited_experiments",
     "legendFormat": "Queued Experiments"
    }
   ]
  },
  {
   "title": "Experiment Details",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "sum by (chaosengine_name) (litmuschaos_passed_experiments) or sum by (chaosengine_name) (litmuschaos_failed_experiments) or sum by (chaosengine_name) (litmuschaos_awaited_experiments)",
     "legendFormat": "Experiment Details"
    }
   ]
  },
  {
   "title": "Passed Experiments",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "litmuschaos_cluster_scoped_passed_experiments",
     "legendFormat": "Passed Experiments"
    }
   ]
  },
  {
   "title": "Failed Experiments",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 14 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "litmuschaos_cluster_scoped_failed_experiments",
     "legendFormat": "Failed Experiments"
    }
   ]
  }
 ]
}